package ClassAndObjects;
//public class Cricketer {
//	String name;
//	int odiRuns;
//	int testRuns;
//	int t20Runs;
//
//	public int totalRuns() {
//		int totalRuns = odiRuns + testRuns + t20Runs;
//		return totalRuns;
//	}
//}
import java.util.Scanner;

public class Solution {
    
    public static void main(String[] args) {
        Scanner scan = new Scanner(System.in);
        int i = scan.nextInt();
        double d = scan.nextDouble();
        scan.nextLine();// to consume extra line generated by inputBuffer in nextDouble 
        String s = scan.nextLine();
        
        System.out.println("String: " + s);
        System.out.println("Double: " + d);
        System.out.println("Int: " + i);
        scan.close();
    }
}